### ISSUE TITLE
Input argument required with git commit -m "..."

### ISSUE THREAD

**Issue by georgezavitsanos** [compilerla/conventional-pre-commit#118]
Hello, I have configured conventional-pre-commit from `.pre-commit-config.yaml file`, 

```
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]

```
However, with _`git commit -m "This is a comment"`_. , I get, 

```
Conventional Commit......................................................Failed
- hook id: conventional-pre-commit
- exit code: 1

usage: conventional-pre-commit
       [-h]
       [--no-color]
       [--force-scope]
       [--scopes SCOPES]
       [--strict]
       [--verbose]
       [types ...]
       input
conventional-pre-commit: error: the following arguments are required: input
```

Please for your advise.
