### ISSUE TITLE
Output of failed hook in vscode without color and from CLI with color possible?

### ISSUE THREAD

**Issue by h0uter** [compilerla/conventional-pre-commit#122]
currently the output log in VSCodelooks like this with default options:

![Image](https://github.com/user-attachments/assets/8dfcdcac-e243-434d-abda-534d9c17099c)

```yaml
default_install_hook_types: [commit-msg, pre-commit]

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--verbose]

```

using `--no-color` arg solves this, but is there a way to support collor in the terminal and no color in vscode?
