### ISSUE TITLE
Switch to `language: system`

### ISSUE THREAD

**Issue by rgnkn** [compilerla/conventional-pre-commit#16]
I suggest this yaml:

```
repos:
  - repo: local
    hooks:
      - id: conventional-pre-commit
        name: Conventional Commit (local)
        entry: bash conventional-pre-commit.sh
        language: system
        stages: [commit-msg]
```

With this it won't be necessary to make the shell-script executable.
