### ISSUE TITLE
Fixup / Autosquash commits

### ISSUE THREAD

**Issue by DanielVoogsgerd** [compilerla/conventional-pre-commit#4]
Hi, I love the pre-commit hook.

I have one small issue with it though. It rejects fixup / squash commits.

fixup / squash / amend commits are only intended for local development, but allow you to amend a commit further in the past than your current HEAD and can be trivially processed using. ```git rebase --autosquash```. This is a really handy feature of git, but it will create commits of the following pattern:

```fixup! Commit message of the old commit to apply the change to```

```squash! Commit message of the old commit to apply the change to```

```amend! Commit message of the old commit to apply the change to```

Obviously, these are rejected by the pre-commit hook. Yet it would be nice if there would at least be an option to allow them until you push

**Comment by bektaskemal** [comment]
For further reference, here is the solution I came up with. It uses no-verify but then runs pre-commit manually after rebase.
https://gist.github.com/bektaskemal/6d3144fc4a28daa0812162ab02f0b6f7

**Comment by JP-Ellis** [comment]
I don't really want to revive an old thread and I understand @thekaveman's reasoning to _not_ include this; however, I do find myself often doing a fixup! or squash! forgetting I have the pre-commit hook, and then having to rerun the command with `--no-verify`. I also think the use of fixup! and squash! should be made possible as they are a part of git's `--autosquash` feature.

As a compromise to a blanket allow, would there be a willingness to allow this behind an option? I'm thinking that the YAML definition could be extended as follows:

```yaml
repos:

# - repo: ...

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: <git sha or tag>
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--allow-autosquash]
```

and the function signature could be changed to

```python
from conventional_pre_commit.format import is_conventional

# prints True
print(is_conventional("feat: this is a conventional commit"))

# prints False
print(is_conventional("fixup! feat: this is a conventional commit"))

# prints False
print(is_conventional("fixup! feat: this is a conventional commit", allow_autosquash=True))
```

The default would remain `false` in both cases so there would be no change in the behaviour of existing code, but should a team wish to allow this, it can be enabled without difficulty.

Let me know if this is something you would be open to and I can send through a PR.

---

Note that ideally, I would prefer it if the YAML definition became:

```yaml
repos:

# - repo: ...

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: <git sha or tag>
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
        allow-autosquash: true
```

but it would appear that pre-commit _only_ allows for customisations to be passed through the `args` key unfortunately. In any case, I don't see a huge issue as someone could have:

```yaml
repos:

# - repo: ...

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: <git sha or tag>
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          - fix
          - feat
          - custom
          - --allow-autosquash
        allow-autosquash: true
```

and I doubt anyone would be confused, or anyone would be actually using `--allow-autosquash` as a commit type.
